import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import Header from "@/components/layout/Header";

const oswald = localFont({
  src: "/fonts/Oswald-VariableFont_wght.ttf",
  variable: "--font-oswald",
  weight: "200 400 600 700",
});
const bebas = localFont({
  src: "./fonts/BebasNeue-Regular.ttf",
  variable: "--font-bebas",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${bebas.variable} antialiased bg-dark_green-400 min-h-screen`}
      >
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
