import type { Metadata } from "next";

import { Bebas_Neue, Oswald } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const oswald = Oswald({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

const bebas = Bebas_Neue({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} ${bebas.className} antialiased bg-dark_green-400 min-h-screen`}
      >
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
